/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Battleship__factory } from "./Battleship__factory";
export { Lock__factory } from "./Lock__factory";
